---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: py-map-api-tls
spec:
  secretName: py-map-api-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "py-map-api.cluster.local"
  dnsNames:
    - "py-map-api.cluster.local"