apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-map-api
  labels:
    app: py-map-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-map-api
  template:
    metadata:
      labels:
        app: py-map-api
    spec:
      containers:
        - name: py-map-api
          image: ghcr.io/rwese/py_map_api@sha256:6a50780b1f4a29689b945a3d47c02f1ef898a2db7e895dbb715c4e434a6e8667
          ports:
            - containerPort: 8000
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
