apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-map-api
  labels:
    app: py-map-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: py-map-api
  template:
    metadata:
      labels:
        app: py-map-api
    spec:
      containers:
        - name: py-map-api
          image: ghcr.io/rwese/py_map_api:sha256-a525dddc42cd8aeb350dd27fbc6f0535fb4f4d67fe4b4b50fcde767028878001
          ports:
            - containerPort: 8000
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
