apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-map-api
  labels:
    app: py-map-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: py-map-api
  template:
    metadata:
      labels:
        app: py-map-api
    spec:
      containers:
        - name: py-map-api
          image: ghcr.io/rwese/py_map_api:sha256-9eb6ff9431431a0b8868ce0b13249db86e1af97098ea5a131931bc6ae4164833
          ports:
            - containerPort: 8000
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
